### ISSUE TITLE
Automatically download tools

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#107]
There are some tools that could be automatically downloaded like nuget. I think we should add support for this in some way.

**Comment by guruDanny67** [comment]
We can try to download them if there are not found in the standard location that the script use: if you don't set the --nuget-path AND the file is not found then we download it, in the correct directory and with an hash/size check to avoid tampering (the size can simply restart the download while the hash will stop the process).
If the user sets the path, even if nothing is found, we can assume that he/she knows what to do and proceed as now.
Maybe also a '--no-tools-download' option can be useful.
Ideally one install the visual studio, python and mingw and all the other tools are downloaded if needed (they can be dependencies of the single project ?)

**Comment by nacho** [comment]
nuget, ninja and meson are now downloaded if needed. I wonder if we should continue with this approach and i.e also download and install cmake and the other tools

**Comment by guruDanny67** [comment]
For Perl I think that is possible and useful, even for cmake there is a .zip available to download and install in the right directory: in a ideal world one install Visual Studio, grab a python 3.4+, msys and all the other programs are download if/when needed.

If we go in this direction (that I like, btw) I think that we should let the (power) user decide to use his/her version of the tools that they may have in some standard (C:\Program data (x86)\...) or not (I put all the dev program under c:\dev, e.g. c:\dev\py35, c:\dev\cmake, c:\dev\tortoiseGit, .even the vs is under c:\dev\vs2013 or c:\dev\vs2015, I'm an old 8.3 dos guy ...) location with command line option, or, better, a configuration file, something like 

-----------------------------
nuget=c:\mystuff\nuget.exe
ninja=c:\test\ninija-dev\ninjia.exe
...
----------------------------

**Comment by nacho** [comment]
As a first step I would make it mandatory, then we can add options

**Comment by guruDanny67** [comment]
Good. It's ok if weI fix the #118 before adding more tools ? I don't like having a solution that can break easily is nice ;(

**Comment by nacho** [comment]
@guruDanny67 I agree we should fix that first

**Comment by guruDanny67** [comment]
I've take a look at the tools and I think we can install easily cmake, perl, nasm & yasm. 
We will use the 32 bit version when there are both the 32 & 64 bit ? 
I was also thinking of using only one directory for all the tools (so there is only one path to add to the build) but in the end it's not a very good idea: first of all if we have separate directory we can have one project using cmake 2.6 and another 3.4 (maybe not some like this but one project that use a beta, unreleased version of meson or ninja can happen) and second if I make a mistake (don't put a dependency, for example) I like to have it happen and appears as soon as possible and not be shadowed because as a test I download all of the tools.
To handle all these paths I tought of putting a method in the projects/tool class to call, automatically, from the build (just before starting the build, really) for all the dependency class.
So if project XX depends from cmake & yasm before calling the build I have the tools\cmake-3.8.x and tools\yasm on the path.
It will be ok or it's too much ?

**Comment by nacho** [comment]
sounds good to me, I just wonder though if we shoudl have tools\win32 and tools\x64... I am also fine to go for 32 bit first and if needed to add the 64bit as well

**Comment by guruDanny67** [comment]
For now, if with the 32 bit version we can build all, I think is ok to use and download that 32 bit version of the tools (that works on a 32 and on a 64 bit O.S.)
Using tools\win32 and tools\x64, based only on the systems we're using to build, can be a good option but me need to hack/hook the projects, just to change the file we need to download (for nasm we may have http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip for the 32 bit version and http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win64/nasm-2.12.02-win64.zip for the 64 bit version): the actual status is way much simpler, one download file and one hash check :)
But probably we can just say that we need a 64 bit machine to build all because, apart from some virtual machines, it's seems to me that every new PC gots a 64 bit version of the O.S. and using the 32 bit it's not a optimal choice (let me explain; it's ok and good to have a 32 bit OS if you have an old portable or a PC with a limited amount of RAM but using that PC to develop and build the Gtk3 stack can be a hard works).

**Comment by nacho** [comment]
We are already proposing msys2 64bit version, I wonder if we should just support 64bit OS

**Comment by guruDanny67** [comment]
IMHO we can use, the 64 bit version as a default. I was thinking of letling the user overwrite the various tools path & name via some set in the environment (e.g. WINGTK_NUGET, WINGTK_NINJIA, ...): having this if you want/need to use the 32 bit version of one program you can use it without problems (but you need to download it manually) but we handle/support/care of only one version (the 64 one).

It's probably also a good thing to make a Tool class (sub classed from project) just to clarify wich is a tool and which is a project.

If I have some time this evening I put down some code and do a PR to see what's coming out.

**Comment by nacho** [comment]
I think we can close this now. Several patches went in and we are in a good state right now.

**Comment by guruDanny67** [comment]
Yes, I agree. 

The only tools that we can download now are yasm & nasm, and check if the msys pkg-config is needed or if we can use the one we build.

**Comment by nacho** [comment]
I saw Fan has projects to build nasm with visual studio, we could have a look at it.

**Comment by guruDanny67** [comment]
I was thinking more of downloading directly the executable, like we do with ninja
