### ISSUE TITLE
SVG icons are not rendered in GTK4 app

### ISSUE THREAD

**Issue by nazar-pc** [wingtk/gvsbuild#1184]
I was trying to figure out why in my GTK4 app (Rust) custom icons are not rendered and so far wasn't able to. Icons shipped with GTK do work though.

They do render on Linux, but not on Windows. I found that librsvg is not compiled by default with gtk4, so I built it separately, but it didn't help.

I was able to convert SVG to PNG successfully with `gdk-pixbuf-thumbnailer.exe`, now wondering what else might be wrong that would prevent custom icons from being rendered.

**Comment by danyeaw** [comment]
Hi @nazar-pc, did you build the hicolor-icon-theme?

**Comment by nazar-pc** [comment]
I did not, I'm not using any icons from default themes, so I didn't think I need them.
Just installed `hicolor-icon-theme` and it made no difference.

**Comment by danyeaw** [comment]
Where are your icons located? We are using svg icons just fine with Gaphor in Windows.

**Comment by nazar-pc** [comment]
They are compiled into the app as resources:
https://github.com/Relm4/icons/blob/9f288c2d65666c7ef1d5a8f5df6401bd5b5f8afa/build.rs#L6652-L6666
And then loaded like this:
```rust
gio::resources_register_include!("resources.gresource").unwrap();

let display = gdk::Display::default().unwrap();
let theme = gtk::IconTheme::for_display(&display);
theme.add_resource_path("/relm4/icons/");
```

I can see then in the inspector as available resources, but application doesn't load them, which I thought might be caused by a specific GTK4 build.

**Comment by nazar-pc** [comment]
The biggest change probably that I don't use libadwaita, I only use GTK4 itself

**Comment by danyeaw** [comment]
Hi @nazar-pc, potentially this is an issue with how resource paths are used with GTK on Windows? Have you tried using an absolute path to the file?

**Comment by nazar-pc** [comment]
I'm using resources and files are included there just fine. I'm not loading icons from disk.

Still not sure what/where is broken, but something clearly is. Here is a thread on the forum with a bunch more details: https://discourse.gnome.org/t/svg-icons-do-not-render-on-windows/18686

**Comment by RustyAngler** [comment]
The GTK-RS book page on installing in Windows:
https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html#install-gtk-4
gives options:
- gvsbuild and MSVC (recommended)
- MSYS2 and GNU toolchain

Using the MSYS2 and GNU toolchain I had NO issues displaying SVG images in a Picture widget and had SVG icons display correctly.
Using the gvsbuild and MSVC install, trying to display svg images in a Picture widget crashed the application and SVG icons (eg "edit_undo_symbolic") are replaced by an error icon.
I am now in a bind, i must use the msvc version due to wanting to use the Opencv-rs library which requires msvc.
I have included librsvg in the gvsbuild/msvc install.

**Comment by nazar-pc** [comment]
Forum thread linked above explains how to get things work after manually moving files around, no idea how to make it "just work" after compilation on Windows :confused:

**Comment by RustyAngler** [comment]
I have tried manually copying the pixbuf lib files in a few different ways, even duplicated the MSYS2+GNU dir structure but have not had any success.

**Comment by nazar-pc** [comment]
Forum describes the only way I found that actually works

**Comment by nazar-pc** [comment]
This works as expected on Windows 11, I no longer care to debug dev environment on Windows 10 and forum post describes how to make release work as well.

**Comment by OSA413** [comment]
If anyone is still trying to figure this out, here's a tip: your app (exe) MUST be in the `bin` directory (DO NOT RENAME `bin` folder), otherwise the `share` and `lib` directories will not be recognized.

App structure should be as the following:
* `whatever/subfolders/you/want/bin/your-app.exe`
* `whatever/subfolders/you/want/bin/gtk4.dlls...`
* `whatever/subfolders/you/want/share/glib-2.0/schemas/gschemas.compiled`
* `whatever/subfolders/you/want/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache`
* `whatever/subfolders/you/want/lib/gdk-pixbuf-2.0/2.10.0/loaders/pixbufloader_svg.dll`
