### ISSUE TITLE
adding gtkmm libraries to the next releases

### ISSUE THREAD

**Issue by alexv-ds** [wingtk/gvsbuild#1346]
The release “Version 2024.5.0 - GTK 4.14.4” contains an archive with compiled dependencies. But there is no gtkmm in it. What about adding gtkmm libraries to the next releases?

**Comment by alexv-ds** [comment]
> Can I ask what you are using Gtkmm for on Windows?

I want to make another email client😅

Currently development is on Linux, but adding gtkmm will reduce the headaches🙂

**Comment by danyeaw** [comment]
Ok cool, would you be interested in making a PR to add Gtkmm to the GTK4 pipeline?

**Comment by pbor** [comment]
This is kind of a slippery slope... let's see the timing with Alex's patch and decide

Maybe we should revise a bit our CI strategy so that:

1. We do "nightly" builds with a fuller target
1. We run a smaller target for normal PRs
1. (optional but it be cool) If the PR contains a `[ci target: foo]` line we would build that target

The last point would also help with testing PR for libs that are not part of the default target

**Comment by danyeaw** [comment]
Hi @pbor, I agree that we should be careful adding too much to the build and to the binaries. It looks like this didn't really change our build time, and it looks like the binaries are about 30mb larger. Maybe we should clearly define what is and what is not part of our core part of GTK4 that we want to provide. For example, libraries like libsoup, glib-networking, and graphene aren't so clear to me - they are definitely GTK related.

I also agree that using something like https://github.com/tj-actions/changed-files to control the pipeline would be really nice to build a much more targeted build for what has changed. Probably for tools updates we'll need to build a wider set of libraries, but we probably don't need to build all of GTK if an unrelated library updates.

**Comment by danyeaw** [comment]
Closed by #1348. Thanks @alexv-ds!
