### ISSUE TITLE
Build json-glib with meson

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#138]
Now that json-glib supports meson I think we can port it to it.

**Comment by guruDanny67** [comment]
Good evening. I take a (fast) look at building with meson and I encounter two problems, related to meson on windows.

The first one is that when importing gnome (for mk_enums, probably) meson looks for python3 that is not existent on windows: I take a look on the github meson project and it talks about the problem but it says it's ok (i'm not convinced ...): to test the build I simply copy my 3.5.2 python.exe as python3.exe but it's not a solution that can be implemented on our side (unless a symboic link under c:\gtk-build\tools\python3-for-meson works).

The other problem arise when ninja/meson is trying to generate the enums and @PERL_PATH@ is not defined (and it seem you get the same error building recipes).

While for some project meson it's ok for complex gnome stuff, on windows, seem difficult to make it work correctly: for example using the reccomended way to identify if the math library is needed on windows fails because the test is made with the cl.exe (passing a /lm.lib to a simple program) that simply ignores options it doesn't recognize so in some linking phase (if I recall, trying to build the gir for gobject introspection) you get an error because the linker, instead, check the library and says that m.lib is not found: as a workaround I get a library I have floating around, rename it to m.lib and copied in the libdir of the stack but it's not a good approach.

I'll take, if I have some time (I'm really busy in this period) a better look at this and try to figure out exaclty what happens and see, on the meson side or maybe patching the file meson.build, if we can resolve this issues because in the long run using meson will be simpler than modify and patch the various visual studio solution/projects (just the fact that you can put the gir/typelib handling directly in the meson file is really useful, when it will work on windows).

**Comment by nacho** [comment]
Ciao Daniele, I guess I would say, file some issues to meson so at least we get some answers to these problems.

**Comment by guruDanny67** [comment]
Pushed a couple of issues on the meson project. It's ok if I add emeus to the projects to build (without the gobject introspection stuff and with visual studio 2015 it will compile ok) ?

Thanks

**Comment by nacho** [comment]
Sure feel free to add emeus

**Comment by guruDanny67** [comment]
On the python3 they answer me now: it's not a meson fault like i thought but of json-glib. It uses:

python3 = find_program('python3')

while the correct way that works (also on windows) is:

python3 = import('python3').find_python()

I'll taking a look at the @PERL_PATH@ issue: if you set it in the glib-mkenums with the correct one (c:\gtk-build\tools\... ) the project will be build: I see if I can meke the build system set it automatically

**Comment by TingPing** [comment]
> I'll taking a look at the @PERL_PATH@ issue: if you set it in the glib-mkenums with the correct one (c:\gtk-build\tools... ) the project will be build: I see if I can meke the build system set it automatically

Alternatively drop the Perl dependency: https://bugzilla.gnome.org/show_bug.cgi?id=779332

**Comment by guruDanny67** [comment]
In the long run it's ok to use python, as it's used already for other tasks (replace.py, for examples).

Actually a put a change on master (by mistake, it was intended to go to a branch, sorry) that, using replace.py, changes not only the version but also the @PERL_PATH@, changing it in a simple perl.exe

In this way, using meson having perl in path (as we do if we put perl as a dependence of json-glib, for example) we can build all without problem,

I was thinking of putting the full perl path on the script (c:\gtk-build\tools\perl\x64\bin\perl.exe) but that would be the correct path that we have when we build glib, not when we use the glib-mkenums script.

In this way on windows the script will not run outside of our build system but since the script is missing an extension on windows, from the command line, the only way I know to launch it is to use explicit perl, something like 'c:\my_stuff\perl_new\bin\perl.exe glib-mkenums' so it0s not a big deal.

BTW i said that meson is not really complete for windows but it was, from my side, a really huge mistake: if used correctly it really helps having all the various script / program run (almost) the same on windows and linux, making really easy handle differents version on Visual Studio.

**Comment by guruDanny67** [comment]
The json-glib modifies upstream, in master, the meson script to look correctly for pyrhon3 and the patch will be cherry picked for the nest 1.2.x stable release so, as soon as it's out, I think we can use meson to build the lib :)

**Comment by nacho** [comment]
@guruDanny67 I see some releases more of json-glib do you think we can get this in now?

**Comment by guruDanny67** [comment]
I'll take a look in this weekend.

Thanks.


Il 20 ott 2017 10:43, "Ignacio Casal Quinteiro" <notifications@github.com>
ha scritto:
