### ISSUE TITLE
Use Meson to build Pango

### ISSUE THREAD

**Issue by ebassi** [wingtk/gvsbuild#170]
Pango's master branch now supports building with [Meson](http://mesonbuild.com).

The Windows build still needs some testing; additionally, it seems a bunch of Windows-only private symbols have been leaking into the `pangowin32` shared library.

**Comment by nacho** [comment]
This I gave it a try, the first problem was fribidi which is already added, but the second is some missing header from harfbuzz. @TingPing I recall you tried and had a similar issue? How did you fix it?

**Comment by nacho** [comment]
We are a bit closer to get this working. I added the missing pc files and now the remaining problem is that for some reason our fontconfig is not exporting all the methods needed by pango. Since we do not have a meson port for fontconfig I guess we should just go ahead and use @fanc999's nmake scripts instead of our custom visual studio projects

**Comment by nacho** [comment]
Done: https://github.com/wingtk/gvsbuild/commit/306ac102134245436f76c660d9936e1b3c572478
