### ISSUE TITLE
Build the new glib with meson

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#250]
Now that we have a new glib we should update it and try to build it with meson. If there are any regressions we should fix them upstream

**Comment by TingPing** [comment]
Fails with:

```
c:\gtk-build\build\win32\release\glib\glib\glibintl.h(16): fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory
```

`libintl.h` ofc exists in `C:\gtk-build\gtk\Win32\release\include`

**Comment by TingPing** [comment]
Ugh, other projects fail with this same error. Ofc nothing is ever reproducable and what works one day on one system is completely broken elsewhere. I give up...

**Comment by xKamuna** [comment]
Copying it into C:\gtk-build\gtk\Win32\release\include\glib-2.0 works.  Maybe that's a hint to help solve it?

**Comment by TingPing** [comment]
That should never be required, it is the default [INCLUDE](https://docs.microsoft.com/en-us/cpp/build/reference/cl-environment-variables) directory and should always be included.

**Comment by xKamuna** [comment]
I'm aware, but I'm just throwing around ideas to help solve the issue, as I encountered it as well.  Copying it is a sufficient solution for me, but of course, for the repository, the underlying issue would need to be fixed, as it must be generic and the problem may cause other issues in the future.  Note that this happens on atk for me, maybe that's another hint.

**Comment by TingPing** [comment]
Yes it happens on atk here also, its possible `meson` is involved overriding `INCLUDE`, I don't know.

The complication to all of this is it works totally fine for @nacho. I can only conclude microsofts compiler hate me.

**Comment by nacho** [comment]
I've tried to build glib and I had no issues when using master. I guess we need to wait for a new tarball.

**Comment by nacho** [comment]
Done

**Comment by guruDanny67** [comment]
@TingPing: It can be something related to #229, so the error is present with some release form vs2017 (15.6.4 from 22.03.2018 has the error, some older version doesn't hae it)
On intermet a couple of days after the vs2017 update someone report the problem to Microsoft and they say ot was reasy for a next updgrade, but not the one out now: there is the same identical error.

BTW Microsoft compiler hates a lot of people, especially when you try to build some complex open source stuff: sometime you simply look deep at the code and you win a complete rebuild, with a full ricompilation & linking of all for no clear (to we human) reason.

The include active before setup all with vcvarsall,bat is been overwritter while pathy, lib & libpath are updated with the vs2017 / sdk stuff.

To close the thing vs2015 use a differente way to create the INCLUDE environment is correct, keeping the original one, normally for these build we have in the include, because we force it before activate the stuff for visualstudio, loading 'Set INCLUDE=c::\gtk-build\gtk\win32\incude' just before launching the vs setup.

I made some test, moving the internal configuration after the vcvarsall.bat but some projects will be ok buf some else doesn't finisch: depending on the stuff  they use (some executable made during the build are found on c:\gtk-build\win32\bin ma that direcoty is present only in the VS stuff: I need to leave the actual load befofe the batch end assert that the new one are presents, addding if missing.

Or patch common7/toool/vsdevcmd/core/winsdk.bat
The line incriminated are:
```
set __tmpwinsdk_include=
if "%INCLUDE%" NEQ "" set "__tmp_include=;%INCLUDE%"
set "INCLUDE=%WindowsSdkDir%include\%WindowsSDKVersion%shared;%WindowsSdkDir%include\%WindowsSDKVersion%um;%WindowsSdkDir%include\%WindowsSDKVersion%winrt;%WindowsSdkDir%include\%WindowsSDKVersion%cppwinrt%__tmpwinsdk_include%"
set __tmpwinsdk_include=
```
The line 
``` if "%INCLUDE%" NEQ "" set "__tmp_include=;%INCLUDE%" ```
should simply be:
``` if "%INCLUDE%" NEQ "" set "__tmpwinsdk_include=;%INCLUDE%" ```
thatì'used, empy or with the corrent/previous INCLUDE. and tahat variable, instead of being always empy is the good one.
