### ISSUE TITLE
meson.build:1:0: ERROR:  Compiler cl can not compile programs.

### ISSUE THREAD

**Issue by akohli74** [wingtk/gvsbuild#266]
Hello,

I'm trying to build this library on Windows 10 x64 with Visual Studio 2017 installed.

I've tried running `vcvarsall.bat amd64` to make sure that all environment variables are set correctly.

When I execute `python .\build.py build -p x64 gtk3`, i get the following error:

```
The Meson build system
Version: 0.46.1
Source dir: C:\gtk-build\build\x64\release\pkg-config
Build dir: C:\gtk-build\build\x64\release\pkg-config-meson
Build type: native build
Project name: pkgconf

meson.build:1:0: ERROR:  Compiler cl can not compile programs.

A full log can be found at C:\gtk-build\build\x64\release\pkg-config-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 361, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 477, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 1289, in build
    Meson.build(self, meson_params='-Dtests=false')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 52, in build
    self.exec_vs(cmd)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 82, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 705, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 737, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python36\python.exe C:\gtk-build\tools\meson-0.46.1\meson.py C:\gtk-build\build\x64\release\pkg-config C:\gtk-build\build\x64\release\pkg-config-meson --prefix C:\gtk-build\gtk\x64\release --buildtype release -Dtests=false' returned non-zero exit status 1.
Error: pkg-config build failed
```

when I check the log at `C:\gtk-build\build\x64\release\pkg-config-meson\meson-logs\meson-log.txt`

it says:

```
Build started at 2018-06-20T12:17:15.170421
Main binary: C:\Python36\python.exe
Python system: Windows
The Meson build system
Version: 0.46.1
Source dir: C:\gtk-build\build\x64\release\pkg-config
Build dir: C:\gtk-build\build\x64\release\pkg-config-meson
Build type: native build
Project name: pkgconf
Sanity testing C compiler: cl
Is cross compiler: False.
Sanity check compiler command line: cl C:\gtk-build\build\x64\release\pkg-config-meson\meson-private\sanitycheckc.c /FeC:\gtk-build\build\x64\release\pkg-config-meson\meson-private\sanitycheckc.exe
Sanity check compile stdout:
sanitycheckc.c
Microsoft (R) Incremental Linker Version 12.00.40629.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:C:\gtk-build\build\x64\release\pkg-config-meson\meson-private\sanitycheckc.exe
sanitycheckc.obj
LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'

-----
Sanity check compile stderr:
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.


-----

meson.build:1:0: ERROR:  Compiler cl can not compile programs.
```

How can I tell the linker where the VS lib path is?  All my environment variables are set correctly in the shell where I'm executing the build.

Thanks!

**Comment by guruDanny67** [comment]
From the linker version (12.0) and the cl version (18.00.xxxxx) it seems
it's not the vs2017 you're using: you may have a vs 2015 installation
laying around.

Try to pass the version & path of the vs installation to the script

2018-06-20 21:25 GMT+02:00 Amrit Kohli <notifications@github.com>:

**Comment by shimondoodkin** [comment]
i had same problem i am using vs2015.
should i use 2017?

**Comment by guruDanny67** [comment]
With the vs 2017 version, even the community one, all the projects are built, in x86 & x64 mode. 

There are some problems with the debug build with the gobject introspection enabled so if you are doing some new project you can use the new one (even if they upgraded it often and sometimes the update breaks everything ;)

If you have a codebase that works with the vs2015 version and you are unsure keep using it: your problem is not, imho, related to a 2015/2017 compiler.

**Comment by akleanthous** [comment]
the problem is that the Microsoft path for the compiler has changed and the script does not account for this:
---------------------------------------------------------------
C:\gtk-build\github\gvsbuild>python .\build.py build --vs-ver 19  -p x64 gtk3
Cleaning up the build environment
Checking msys tool
Checking Msvc tool

Visual studio installation(s) found:
    Visual Studio Professional 2017 @ C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
    Visual Studio Professional 2019 @ C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional

Error:
  'C:\Program Files (x86)\Microsoft Visual Studio 19.0\VC\Auxiliary\Build\vcvars64.bat' could not be found.
  Please check you have Visual Studio installed at 'C:\Program Files (x86)\Microsoft Visual Studio 19.0'
  and that it supports the target platform 'x64'.
---------------------------------------------------------------------------------
Clearly the path the compiler is searching for does not exist. I tried to produce the path but run into other problems and gave up.

**Comment by guruDanny67** [comment]
The vs2019 compiler is version 16 and the vs2017 is 15.

For the standard installation all you have to do is pass the correct version, so --vs-ver 16 for vs2019 or --vs-ver 15 for the 2017. The script looks for the correct directory, trying the professional, community, enterprise or build tool until it finds one installed.

**Comment by akleanthous** [comment]
guruDanny67 hello,
Thank you for the correction. I used: 
python .\build.py build --vs-ver 16 -p x64 gtk3
and worked OK. Thanks.

**Comment by guruDanny67** [comment]
Thanks, the vs version is really a mess, anytime I need some information I
have to go back, again and again, to the Wikipedia page to try to clarify
all.

And with the new runtime, it's not so clear to another level: the vs2015
(Visual Studio version 14) is runtime vs140 (so you have vs2015, vs-ver 14
and runtime 140, good), vs2017 (--vs-ver 15) is vs141 (why?) and the vs2019
is, now, vs142  but I think that, sooner or later, some vs2019 runtime will
jump to vs150, or to vs152 just to keep some compatibility  :(

Any rule you try to set up (drop 2 from the year to get the version ...) is
useless, just use a table or,  as I said before, put a link to the
Wikipedia page on your browser :)

There are surely good reasons for all of this but, especially from someone
not from the USA (the jump from vs12 to vs14 because 13 is not good ...)
sometimes it's really complicated


   With Best Regards
    Daniele Forghieri


Il giorno ven 21 giu 2019 alle ore 09:29 akleanthous <
notifications@github.com> ha scritto:

**Comment by zzt112358** [comment]
Thank you for solving many of my problems. 
On my computer, the script recognizes Visual Studio 2019 as 12 and can only be installed by the command: python .\build.py build --vs-ver 16 -p x64 gtk3
