### ISSUE TITLE
Have a way to build ffmpeg without gpl

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#286]
@guruDanny67 I recall you added a way to enable gi, is it possible to have something like --enable-gpl for a specific project? i.e ffmpeg

**Comment by guruDanny67** [comment]
if it's only some parameter(s) to add to the exec_vs command is surely
doable, adding something like '--ffmpeg-enable-gpl' to the parser.

Then in the ffmpeg build() method add the '--enable-gpl' to the command
line if self.opts.ffmpeg_enable_gpl is True.

The --enable-gi was a little bit complicated because I have to change the
dependencies and, having to use it in more than one project, I changed also
the meson build param building it piece by piece with a list (that, btw, we
should also put on the cmake builder and the others because, to me, seems
clearer).

A can try something this evening



Il giorno lun 24 set 2018 alle ore 10:41 Ignacio Casal Quinteiro <
notifications@github.com> ha scritto:

**Comment by guruDanny67** [comment]
I put a branch on github, starting from your branch, to make the ffmpeg gpl part optional.

If it's ok feel free to merge it (maybe correct/improve the option description, thanks).

I also change the command to have the full bash path because on some configuration I have a bash on the windows path (if you try to install some linux subsystem) that is found before the msys one so the build terminate with an error (a cryptic one, something like "you can download a linux subsystem from the window store").

With best regards

**Comment by nacho** [comment]
@guruDanny67 the patch looks good to me. I wonder if in the future we should have some mechanism to provide per project options in a generic way. Maybe having some virtual method or something... I am pushing your patch to master. Thanks!

**Comment by guruDanny67** [comment]
Yes, it's something I was thinking about for some time, for example to
enable the broadway backend for gtk.

I remember, with mplayer, that for the filters you put something like this
on the command line for configuring them

--vf_filters rescale=1024:768,framestep=25,...

We can make something like this for the project list, so we shioud have

build.py ... gtk3=version:3.22,backend=broadway

build.py ... ffmpeg=enable_gpl

In this way we don't pollute the parser and the options remain local to the
project










Il giorno mar 25 set 2018 alle ore 10:35 Ignacio Casal Quinteiro <
notifications@github.com> ha scritto:
