### ISSUE TITLE
Properly create tarballs out of the projects

### ISSUE THREAD

**Issue by nacho** [wingtk/gvsbuild#326]
Right now we download the tarballs and put them in the src directory. In the case of the git repos we also create a tarball out of them.

I think we need the following:
 - we should have another directory i.e "tarballs"
 - the tarball expander should take the tarball from src and all the patches, zip it and put it in "tarballs"
 - the git repos should take the git repo without the .git folder and create a zip (should we just use git archive for this?), take this zip + the patches and create another zip

The reason is that in order to be compliant with the lgpl we need to provide the source code including any patch.

**Comment by guruDanny67** [comment]
Hi. I thinking about it yesterday. 

What about putting, under the built binary directory (e.g. c:\gtk-build\gtk\release) a src directory (so we have bin, lib, doc, ..., src) with the original tarball (downloaded or from git) and a copy of our patches?

Apart from gettext all the other patches dir are small and make a tar from the already compressed files seem overkill.

In this way you are also pretty sure that you have the correct files because are 'linked' to the build phase: if you want you get all, if you don't want the source you skip only the src dir but you don't have to go in export and choose the ones for your particular built.

Thoughts ?

Thanks.

**Comment by nacho** [comment]
I am fine with that idea, although I really need this to be a tarball since I want to have a single url for it. Note I made the same thing for jhbuild

**Comment by guruDanny67** [comment]
After we have the dir with all under it making a tarball/zipfile should be really simple, just a function call.
