### ISSUE TITLE
pypi support

### ISSUE THREAD

**Issue by behrisch** [wingtk/gvsbuild#329]
I am currently looking for an easy way to ship a python application which uses pygobject. Would it be possible to upload at least the generated wheels to PyPI? I think this can even be automated with appveyor, see https://packaging.python.org/guides/supporting-windows-using-appveyor/#automatically-uploading-wheels.

**Comment by danyeaw** [comment]
I am not sure if this would work because it isn't enough to have just the wheels, you need to ship all the Gtk libraries with your app. Right now, I think you could build gvsbuild and then run PyInstaller on your app, and then ship your application. To prevent rebuilding every time CI is run for your app, you could make use of the CI cache. In the future, maybe we could set up the CI to post the built version of GTK, like gtk-win use to provide, and then the libraries could be installed instead of rebuilt.

**Comment by behrisch** [comment]
In our case we solved it using a mingw build
