### ISSUE TITLE
Visual Studio > 2017

### ISSUE THREAD

**Issue by adelphiaUK** [wingtk/gvsbuild#367]
This is not so much an issue as a request. I have VS 2019 Enterprise on my system as I have a developers license with Microsoft. However, I am trying to find where I can change (or add) the VS path of my own installation so that the build completes.

Where in the script files or dependencies can I change the path from "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\Auxiliary\Build\vcvars64.bat" to "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" so that the build process will complete.

**Comment by mhertz** [comment]
'--vs-install-path=', e.g. I use for VC buildtools 2019:
'--vs-install-path="c:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"'. 

You just add the path just before the 'VC\Auxiliary\Build\vcvars64.bat', as that part is standard I believe, for the various editions.

Note, I honestly haven't tested if needed, and guessing not, but I also run preceddingly(in my building batchfile):

'cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build"
call vcvars64.bat
'
As used another persons building batchfile for inspiration, which used such(or just call the vcvars64.bat directly from it's path, don't know why I specifically CD into it first, but along time since I made that file).

There's several other parameters, if you check the docs, e.g. for VC edition and such, which maybe also would work instead, but after struggling with the issue you described, and finding a fix, then left it at that.

**Comment by guruDanny67** [comment]
If you use the default install dir you have only to set the vs version (for Visual Studio 2019 is 16) and the script should get the correct directory, trying the professional, enterprise, community and buildtool dir until it finds one so:

python build.py build  -vs-ver 16 [other options] projects 

should be enough to get and set up the compiler & linker.

There is no need to manually call the vcvars64.bat before the script because the script doesn't use that information but every time a new environment is created (the script tries very hard to avoid to depends on what's called and set before the launch so the builds are reproducible).

With best regards.

**Comment by mhertz** [comment]
Thank you Danny for help and elaborating, much appreciated, and sorry adelphiaUK for "clumsy", or non-optimal help.

**Comment by adelphiaUK** [comment]
@mhertz that's no problem. You tried and I basically understood what you said. I do want to say thanks also to @guruDanny67 for explaining how to use it in a simpler form.

As a shortcut, I installed the base install of VS2013 such that I could complete, but then I ran into another error so didn't complete.

I will try again with 2019 (as I've uninstalled 2013 already) using the suggested approach and see how far I get this time! I'm just desperate to get a running copy of a fully fledged Deluge GUI for Windows as it appears the one I use is no longer supported.

**Comment by guruDanny67** [comment]
We should have better documentation that explains this kind of issues (depending on your installation the system can get the wrong mkdir or link command so, in the script startup, only the path that starts with "C:\windows\" or contains '\git\' are kept, the other are dropped).

**Comment by mhertz** [comment]
Thanks adelphiaUK and Danny as usual :)

Btw, just in case you didn't know, then for inspiration check doadin's repo for building gvsbuild and everything else needed for deluge2 on windows:

https://github.com/doadin/DelugeBuildFromSource

Also, I myself built and provided an unofficial deluge2 windows installer, though just stopped doing(I don't use windows myself, and was just to help out in meantime of waiting for official installer to emerge), but will be taken over soon by petersasi:

https://forum.deluge-torrent.org/viewtopic.php?f=12&t=55463

Sorry for off-topic, but just saw that you mentioned this was for deluge2, which also was my usage of gvsbuild :)

**Comment by adelphiaUK** [comment]
As a GUI for Deluge 2 is my main goal (although I appear to have completely screwed up my ubuntu Virtualbox now) I wouldn't say it was off topic, but perhaps something that shouldn't really be discussed in an "issue"  slot on github. I only started to look into creating my own GUI as you stated the project was no longer supported / maintained in the forum you linked to (which is where I got my idea from in the first place.

**Comment by mhertz** [comment]
The installers btw is fine and very recent too, and I just added that notion about unsupported to state that i'm not releasing new builds in feature, though as said, petersasi voluntered to build them in feature, from the build scripts I just posted to him, though e.g official deluge installers also have maybe 6 - 12 months or more between releases, so alittle time without updated builds shouldn't really mater, also as changes has been so small for long time coming mostly anyways.

If you want you can take a fresh gvsbuild from the 7z archive I posted in that thread on deluge forum, it's latest compile from gtk-3-24 branch and not the little older used in regular gvsbuild here, and is under deluge2\overlay\data.

I fully agree with your post above(thank you), and will shut up now about that and will let you return with support questions to devs or others in the know if having more issues and hopefully can get your VM back up on track again.

Good luck :)

**Comment by adelphiaUK** [comment]
One last post (with the ability of you to reply before I close the issue) and that is, are you active on the Deluge forum still? I know you';re not doing any active builds / releases but if you are available in case I have any general or even specific issues I may need help with, would you be available?

**Comment by mhertz** [comment]
Yes :) I recognize that I wrote in that thread "CU around the forums", which was I now see a wrongful way to say "in other subsections of this forum" e.g Linux section etc, as kinda thought the thread would die out, and normally I'm not much in the windows section, except that thread. 

That said, I can often not be of much help though, as usually issues are deluge2 related and not related to my changes, so need directed upstream instead, as I'm not clever enough usually to know my way around the deluge internal code, but I do what I can of-course if anybody has a question to something, still.

**Comment by adelphiaUK** [comment]
Thanks. I'll take a look and will add you as a followship member (hmm, followship. Perhaps I should TM that ;)). CU on the flip side!
