### ISSUE TITLE
How to build GTK application with Visual Studio 2019?

### ISSUE THREAD

**Issue by JasonLCY3** [wingtk/gvsbuild#405]
I follow the guide of [Setting up GTK for Windows](https://www.gtk.org/docs/installations/windows) which tells me to use gvsbuild if I prefer developing using Visual Studio.
```
Project(s) built:
    nuget                     (1.534 s)
    python                    (48.783 s)
    ninja                     (1.526 s)
    meson                     (8.023 s)
    pkg-config                (19.918 s)
    cmake                     (9.735 s)
    win-iconv                 (10.585 s)
    gettext                   (94.590 s)
    libffi                    (34.307 s)
    zlib                      (6.370 s)
    glib                      (174.259 s)
    atk                       (25.957 s)
    nasm                      (1.558 s)
    libjpeg-turbo             (45.699 s)
    libtiff-4                 (74.815 s)
    jasper                    (25.948 s)
    libpng                    (17.437 s)
    gdk-pixbuf                (48.652 s)
    freetype                  (16.211 s)
    libxml2                   (43.074 s)
    fontconfig                (25.394 s)
    pixman                    (22.683 s)
    cairo                     (132.593 s)
    harfbuzz                  (65.285 s)
    fribidi                   (27.002 s)
    pango                     (30.748 s)
    libepoxy                  (29.013 s)
    gtk3                      (237.989 s)
```
After the script is done, how can I build GTK application?

![image](https://user-images.githubusercontent.com/24191781/100903271-a8036900-3500-11eb-9f06-30b00fc7c8a6.png)
Do I need to link individual headers file one by one?
One more question, how can I install gtkmm with this script and use it in Visual Studio?

**Comment by guruDanny67** [comment]
The easiest way I find to use the gtk stack for a project is to use meson & pkg-config to generate a ninja build file (so you can build from the command line) or, from the same files, a Visual Studio Solution that you can open, build & debug with the IDE.

Take a look at the check-libs project in the script to have an idea of what you have to do to build you project.

For the gtkmm libraries I start to build them, have some success but it's not finished: if I have time in the next future, maybe because of some lockdown :( I'll try to update it to have something but don't hold your breath.

With best regards
