### ISSUE TITLE
Add CMake Support

### ISSUE THREAD

**Issue by Febbe** [wingtk/gvsbuild#604]
CMake is one of the most popular build environment with round about 30%. Therefore, it would be good, to add CMake Config files for all libraries shipped via gvsbuild. This would make it easier to integrate it in other CMake projects without the hassle to write own Find Modules.

**Comment by nacho** [comment]
For that you have vcpkg which already uses CMake, in gvsbuild we are more interesting to use either meson or whatever is the build system the project provides.

**Comment by Febbe** [comment]
Vcpkg currently does not ship gtk3. The provided version ist outdated and broken.
Also, to ship cmake-config files does not mean, you should change buildsystems. Even meson can create cmake-config files. Those files only define a library, which version it is and in which relative directory the corresponding lib/DLL and header files are stored.
All those are project/build dependent.

**Comment by nacho** [comment]
Are you willing to maintain it and provide patches to have it in gvsbuild?

**Comment by eli-schwartz** [comment]
> Therefore, it would be good, to add CMake Config files for all libraries shipped via gvsbuild.

But the existing pkg-config files for all libraries shipped via gvsbuild, come from the libraries themselves which create the pkg-config files.

Writing cmake config files would require maintaining those outside of the libraries themselves, with potentially highly divergent contents and painful syncing requirements.

I'm not really sure I understand the point of it all, since pkg-config is fully usable on Windows, from cmake. Just install pkgconf for Windows, and use `pkg_check_modules()` in cmake.

> Also, to ship cmake-config files does not mean, you should change buildsystems. Even meson can create cmake-config files.

If you want gtk4 and friends to provide a gtk4-config.cmake etc. created by meson, then isn't that something you should ask upstream gtk to create?
