### ISSUE TITLE
libpng build failure

### ISSUE THREAD

**Issue by comotion** [wingtk/gvsbuild#898]
Hi,
I had trouble building pygobject due to libpng issue finding checksym.awk
command used is ` gvsbuild.exe build --platform x86 --enable-gi --py-wheel gobject-introspection pycairo pygobject`:

![image](https://user-images.githubusercontent.com/62794/226568163-8a6df6d7-b178-4ad2-9a70-6f579ec6bbf0.png)

Fixed by putting checksym.awk from https://gitweb.geodns-global.gentoo.org/proj/codec/ghostscript-gpl-patches.git/plain/libpng/scripts/checksym.awk?h=ghostscript-9 into the `libpng/gvsbuild-cmake/scripts` folder.

This is on Windows 10, using latest anaconda.

**Comment by BlossomiShymae** [comment]
Hiya!

I may have encountered a similar issue since I get an `Error: libgpng build failed`. Wasn't able to resolve with `--clean` or `--from-scratch` flags either. The solution of downloading the **checksym.awk** file into `libpng/gvsbuild-cmake/scripts` totes fixed it for me! ＾▽＾♡

-  Windows 10 (Version 22H2 Build 19045)
- Python 3.8.3
- `gvsbuild build gtk4`

![image](https://github.com/wingtk/gvsbuild/assets/87099578/f8742bc1-12fc-40db-bc41-a08ea4de3e0d)

**Comment by danyeaw** [comment]
@comotion I noticed you were using the x86 platform option, are you really on 32-bit hardware with Windows 10?

@BlossomiShymae were you using that build option as well?

**Comment by BlossomiShymae** [comment]
I apologize for the erroneous feedback. u.u

I was using **Git Bash** and not **Powershell** as the README recommended. I'm not able to reproduce the lbgpng failure with Powershell from clean/scratch. It could be something to do with the Bash shell.

It works properly when following the README strictly. (●'◡'●)
